// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhwyEgnMgs8bIWPuaDJkk_Noj1bRRmC0',
    appId: '1:486076073048:web:c2deb2a93e0615596bf62d',
    messagingSenderId: '486076073048',
    projectId: 'fir-test-40ebf',
    authDomain: 'fir-test-40ebf.firebaseapp.com',
    storageBucket: 'fir-test-40ebf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSCMigTBZ0yCp0DpfOcGTF44Ark8N2RLo',
    appId: '1:486076073048:android:bebac5cd330e7a806bf62d',
    messagingSenderId: '486076073048',
    projectId: 'fir-test-40ebf',
    storageBucket: 'fir-test-40ebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcmwZtH7Phch6djhlSrkigheBJnsWED1w',
    appId: '1:486076073048:ios:8e7676ffc58731d96bf62d',
    messagingSenderId: '486076073048',
    projectId: 'fir-test-40ebf',
    storageBucket: 'fir-test-40ebf.appspot.com',
    iosBundleId: 'com.example.firetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcmwZtH7Phch6djhlSrkigheBJnsWED1w',
    appId: '1:486076073048:ios:8e7676ffc58731d96bf62d',
    messagingSenderId: '486076073048',
    projectId: 'fir-test-40ebf',
    storageBucket: 'fir-test-40ebf.appspot.com',
    iosBundleId: 'com.example.firetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnhwyEgnMgs8bIWPuaDJkk_Noj1bRRmC0',
    appId: '1:486076073048:web:709c7215449d44af6bf62d',
    messagingSenderId: '486076073048',
    projectId: 'fir-test-40ebf',
    authDomain: 'fir-test-40ebf.firebaseapp.com',
    storageBucket: 'fir-test-40ebf.appspot.com',
  );
}
